### PR TITLE
Integration with https://github.com/jonathanpenn/ui-screen-shooter

### PR DESCRIPTION
**Pull request by fulldecent**
Please test and comment on this in conjunction with:

https://github.com/fulldecent/itc-localized-screenshot-uploader
https://github.com/fulldecent/ui-screen-shooter

SEE ALSO: https://github.com/jonathanpenn/ui-screen-shooter/pull/20

### CODE REVIEW

**Comment by fulldecent** [comment]
This is looking better now.

I have successfully uploaded to iTunes using this.

**Comment by fulldecent** [comment]
Could you please take a look at this, the other side has made the commit

**Comment by jonathanpenn** [comment]
I'd like to see this kind of thing, too. Obviously. :)

**Comment by fulldecent** [comment]
Is this project still alive?

**Comment by fulldecent** [comment]
Bump

**Comment by rhaining** [comment]
Ack, sorry y'all!  I was in transition between jobs when this came through earlier in the year. i'll take a look!

**Pull request merged**
